### ISSUE TITLE
Add supporting of primitive arrays

### ISSUE THREAD

**Issue by MaksHladki** [nartc/automapper-transformer-plugin#10]
Hi. I found an issue when the model uses an array with primitive types as a property.
I used your [example](https://github.com/nartc/automapper-transformer-plugin-examples) for testing.
Please update User* models to use string array instead of the `Address` one.

```javascript
export class User {
  firstName!: string;
  lastName!: string;
  profile!: Profile;
  addresses!: string[];
}

export class UserVm {
  first!: string;
  last!: string;
  full!: string;
  profile!: ProfileVm;
  addresses!: string[];
}

export class UserVm {
  first!: string;
  last!: string;
  full!: string;
  profile!: ProfileVm;
  addresses!: string[];
}

```
Then try to build the app, you will see an exception `TypeError: Cannot read property 'transformFlags' of undefined`. 
I hope it wouldn't be very difficult to fix.

**Comment by nartc** [comment]
Oh man this is embarassing xD. Yeah, it wouldn’t be difficult to fix but idk why I didn’t really think of all the cases. Do you mind submit a PR (even just a markdown file) to list all the cases you could think of?
