### ISSUE TITLE
Can't Resolve classes in a different .ts file

### ISSUE THREAD

**Issue by sarathfrancis90** [nartc/automapper-transformer-plugin#94]
I am facing an issue when using the automapper transformer plugin with nestjsx-automapper.
I have added the plugin info in nest-cli.json file.

Transformer Plugin unable to resolve class defined in a separate .ts file.

Details

Versions:
NestJs: 7.4.2
nestjsx-automapper: 3.1.2
@nartc/automapper-transformer-plugin: 1.0.21
typescript: 3.7.4

Example.
There is `profile.ts` file with following.

```ts
export class Profile {
  bio: string;
  age: number;
}
```

and there is user.ts file with

```ts
import { Profile } from './profile'
export class User {
  firstName: string;
  lastName: string;
  profile: Profile;
}
```

when building the project, error is thrown stating, Can't Resolve Profile from the User Class.

Please advise. 

Thanks,

**Comment by nartc** [comment]
Thanks for reporting. I'll take a look as soon as possible.

**Comment by sarathfrancis90** [comment]
@nartc :Any update on this?

**Comment by nartc** [comment]
@sarathfrancis90 Hi, I'm in a middle of transitioning to a new job so kind of busy at the moment. I'll get to the issue as soon as I can. Thank you for your patience.

**Comment by nartc** [comment]
@sarathfrancis90 I can't seem to reproduce this issue. Can you please provide a sample repository?
